In [1]:
import torch
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])

C:\Users\admin\AppData\Local\Temp/ipykernel_9476/1646494204.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1463.)
  _ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])


In [7]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t

tensor([[[ 1.1037e+00,  1.4392e+00, -3.5836e-01,  7.9435e-01,  6.7121e-01],
         [-1.0970e+00, -4.2297e-01, -2.4045e-03, -5.7709e-02,  1.4724e-01],
         [-1.7418e+00, -2.7463e-02, -3.7804e-01, -7.6358e-02,  3.0472e-01],
         [ 1.5840e+00,  3.3846e-01,  5.2824e-01, -1.2366e+00, -2.8236e-01],
         [ 6.9662e-01,  7.4696e-01, -6.6031e-01,  4.3189e-02,  1.0318e+00]],

        [[-6.3548e-01, -2.8791e-01,  2.1660e-01,  5.3436e-01,  1.2432e+00],
         [-8.6601e-01,  1.9191e+00,  1.4561e+00, -4.0465e-01,  1.5083e-01],
         [ 4.2625e-01, -1.6505e+00,  9.8866e-01,  5.9331e-01, -1.2580e+00],
         [-4.2954e-01, -6.3082e-01, -2.2976e-01,  6.6967e-01, -1.1209e+00],
         [-1.3493e+00,  7.5996e-01,  1.7215e+00,  1.0247e+00, -2.4673e-01]],

        [[ 1.2862e+00,  2.4867e+00,  1.1233e+00, -1.2427e-01,  3.9728e-01],
         [ 5.5449e-01, -1.4797e+00, -1.3597e+00,  3.5796e-01, -1.2417e+00],
         [-1.6472e+00,  7.0296e-01, -9.4466e-01, -3.6383e-01,  2.7250e-02],
        

In [10]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[-6.5665e-01, -2.3059e-01,  1.9732e-01,  3.8371e-01, -1.6790e-01],
          [-5.4958e-02, -7.7166e-01,  7.6009e-01, -6.3151e-01,  7.5304e-01],
          [ 2.6778e-01,  6.7157e-01, -1.1553e+00,  1.5891e+00, -1.9389e-01],
          [-8.2352e-01,  8.7794e-01,  1.6703e-02,  1.3123e+00,  6.7534e-01],
          [-1.3656e+00, -1.2980e-01,  1.1097e-01, -8.1000e-01, -6.0951e-01]],

         [[ 2.3078e-01, -1.0925e+00, -1.7024e-01,  8.8689e-01,  6.9142e-01],
          [ 3.8064e-01,  7.1490e-01,  8.8415e-01, -2.3650e-02, -1.6536e+00],
          [ 1.8148e+00, -4.1126e-01,  1.8979e-01,  1.3921e+00, -9.0453e-02],
          [ 9.5413e-01,  1.7635e+00,  8.0903e-01,  1.4688e+00, -1.6528e+00],
          [-1.0375e+00,  1.2199e+00,  5.4941e-01,  6.1756e-01, -9.1349e-01]],

         [[-4.0098e-02, -2.3632e+00,  6.4505e-01,  2.7197e-01, -4.8096e-01],
          [-2.5121e-01,  7.9613e-01,  1.7434e+00,  2.6449e-01,  1.4592e+00],
          [-6.2176e-01, -1.3081e+00, -9.1573e-01, -4.0822e-01, -1.1428e+

In [11]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [12]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [13]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [14]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [8]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [9]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [10]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [11]:
try:
    gray_named = (img_named[..., :3] * weights_named).sum('channels')
except Exception as e:
    print(e)

Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.


In [12]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))